import { mapPlantDetailsToDetail } from './detailMappers';

describe('mapPlantDetailsToDetail', () => {
  it('maps details with sections', () => {
    const detail = mapPlantDetailsToDetail(
      {
        id: '1',
        commonName: 'Rose',
        scientificName: 'Rosa',
        scientificNames: ['Rosa'],
        otherNames: ['Garden rose'],
        imageUrl: 'image',
        family: 'Rosaceae',
        genus: 'Rosa',
        origin: ['Europe'],
        type: 'shrub',
        dimensions: { type: 'height', min: 1, max: 1.5, unit: 'feet' },
        year: null,
        edible: true,
        poisonous: false,
        cycle: 'perennial',
        watering: 'average',
        wateringGeneralBenchmark: { value: '5-7', unit: 'days' },
        sunlight: ['full sun'],
        pruningMonth: ['March'],
        pruningCount: { amount: 1, interval: 'yearly' },
        seeds: 0,
        attracts: ['bees'],
        propagation: ['seed'],
        hardiness: { min: 3, max: 8 },
        flowers: true,
        floweringSeason: 'Spring',
        soil: ['Well-drained'],
        pestSusceptibility: ['Aphids'],
        cones: false,
        fruits: false,
        edibleFruit: false,
        fruitingSeason: null,
        harvestSeason: null,
        harvestMethod: null,
        leaf: true,
        edibleLeaf: false,
        growthRate: 'High',
        maintenance: 'Low',
        medicinal: true,
        poisonousToHumans: false,
        poisonousToPets: false,
        droughtTolerant: false,
        saltTolerant: false,
        thorny: false,
        invasive: false,
        rare: false,
        tropical: false,
        cuisine: false,
        indoor: false,
        careLevel: 'Medium',
        plantAnatomy: [{ part: 'leaves', colors: ['dark-green'] }],
        description: 'Pretty',
      },
    );

    expect(detail.images).toHaveLength(1);
    expect(detail.care.length).toBeGreaterThan(0);
    expect(detail.growth.length).toBeGreaterThan(0);
    expect(detail.seasonal.length).toBeGreaterThan(0);
  });

  it('handles missing optional data', () => {
    const detail = mapPlantDetailsToDetail(
      {
        id: '2',
        commonName: null,
        scientificName: 'Abies',
        scientificNames: null,
        otherNames: null,
        imageUrl: null,
        family: null,
        genus: null,
        origin: null,
        type: null,
        dimensions: null,
        year: null,
        edible: null,
        poisonous: null,
        cycle: null,
        watering: null,
        wateringGeneralBenchmark: null,
        sunlight: null,
        pruningMonth: null,
        pruningCount: null,
        seeds: null,
        attracts: null,
        propagation: null,
        hardiness: null,
        flowers: null,
        floweringSeason: null,
        soil: null,
        pestSusceptibility: null,
        cones: null,
        fruits: null,
        edibleFruit: null,
        fruitingSeason: null,
        harvestSeason: null,
        harvestMethod: null,
        leaf: null,
        edibleLeaf: null,
        growthRate: null,
        maintenance: null,
        medicinal: null,
        poisonousToHumans: null,
        poisonousToPets: null,
        droughtTolerant: null,
        saltTolerant: null,
        thorny: null,
        invasive: null,
        rare: null,
        tropical: null,
        cuisine: null,
        indoor: null,
        careLevel: null,
        plantAnatomy: null,
        description: null,
      },
    );

    expect(detail.images).toHaveLength(0);
    expect(detail.care).toHaveLength(0);
    expect(detail.growth).toHaveLength(0);
    expect(detail.seasonal).toHaveLength(0);
  });
});
